### PR TITLE
Swift4 migration

### PR DESCRIPTION
**Pull request by pteasima**
Naively migrated of all VTree code to Swift4, carthage dependencies remain in swift3. Tests pass and everything seems to work.

### CODE REVIEW

**Comment by pteasima** [comment]
Hi inamyi, thank you for this awesome repo. Have you given up on it or do you still expect that this could become active in the future?
Ive played around with this quite a lot in the past but ended up in a huge mess which could never be pushed back into your repo. This time around, I have some ideas how I would like to improve VTree and would like to do this in a more incremental way.

Let me know if I should bother with pull requests or if I should just maintain my own fork. Im not sure if I will be able to implement anything useful, but iOS needs a VDOM so badly that Im willing to spend time trying.

**Comment by pteasima** [comment]
I also got rid of swiftlint warnings on this same branch. If you dont want this included in the pull request, let me know. Note tham Im using default xcode editor settings + I added swiftlint autocorrect to the swiftlint runscript (mainly because xcode likes to indent whitespace only lines which violates a swiftlint rule but can be autocorrected)

**Comment by pteasima** [comment]
I cant automigrate the VTreeTests target. It fails on "no such module VTree". I havent bothered solving this.

**Comment by inamiy** [comment]
Hi, sorry for super late reply 😅

Swift 4 support is done in https://github.com/inamiy/VTree/pull/11 without having many breaking changes, so I think this PR is OK to close now.

Thanks for contribution anyway!

**Comment by pteasima** [comment]
forgot about this too tbh ;)

**Pull request closed without merging**
